rvm:
  - 2.2.3
before_script:
  - RAKE_ENV=test rake db:migrate:reset db:test:prepare
  - psql -c 'CREATE USER workshops WITH SUPERUSER;' -U postgres
  - psql -c 'create database workshops_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rspec
addons:
  postgresql: '9.3'
services:
  - postgresql
