rvm:
  - 2.2.3
before_script:
  - psql -c 'CREATE USER workshops;' -U postgres
  - psql -c 'ALTER USER workshops WITH SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE workshops_development;' -U postgres
  - cp config/database.yml.sample config/database.yml
services:
  - postgresql
addons:
  postgresql: '9.3'
